/**
 * Toute la copy francaise du portail client, centralisee pour permettre une
 * duplication EN ulterieure (meme philosophie que src/lib/i18n/dictionaries).
 * Regle d'ecriture : jamais de tiret long, phrases simples.
 */
export const portalStrings = {
  appName: 'Portail client',
  brand: 'Lucid-Lab',

  nav: {
    home: 'Accueil',
    projects: 'Projets',
    requests: 'Support',
    meetings: 'Réunions',
    billing: 'Facturation',
    documents: 'Documents',
    website: 'Site web',
    info: 'Mes informations',
    logout: 'Déconnexion',
  },

  login: {
    title: 'Connexion à votre espace client',
    subtitle: 'Saisissez votre adresse email. Vous recevrez un lien de connexion sécurisé, sans mot de passe.',
    emailLabel: 'Adresse email',
    emailPlaceholder: 'vous@entreprise.fr',
    submit: 'Recevoir mon lien de connexion',
    sentTitle: 'Vérifiez votre boîte mail',
    sentBody: 'Si un compte existe pour cette adresse, un lien de connexion vient de vous être envoyé. Il est valable 15 minutes.',
    resend: 'Renvoyer un lien',
    errorInvalid: 'Ce lien de connexion est invalide ou a déjà été utilisé. Demandez un nouveau lien ci-dessous.',
    errorExpired: 'Ce lien de connexion a expiré. Demandez un nouveau lien ci-dessous.',
    errorRevoked: "L'accès au portail n'est pas actif pour ce compte. Contactez votre interlocuteur Lucid-Lab.",
    help: 'Un souci pour vous connecter ? Écrivez-nous à info@lucid-lab.fr.',
  },

  verify: {
    title: 'Connexion au portail',
    body: 'Cliquez sur le bouton ci-dessous pour ouvrir votre espace client sécurisé.',
    submit: 'Se connecter au portail',
    missingToken: 'Ce lien est incomplet. Ouvrez le lien reçu par email ou demandez un nouveau lien de connexion.',
    backToLogin: 'Demander un nouveau lien',
  },

  home: {
    greeting: 'Bonjour',
    intro: 'Voici votre espace client Lucid-Lab. Suivez vos projets, vos documents et vos factures, et échangez avec nous au même endroit.',
    openTasks: 'Tâches en cours',
    nextStep: 'Prochaine étape',
    nextStepDue: 'Prévu pour le',
    pendingRequests: 'En attente de votre action',
    dueInvoices: 'Factures à régler',
    lastMeeting: 'Dernier échange',
    nothingOpen: 'Rien ne demande votre attention pour le moment.',
    seeAll: 'Tout voir',
  },

  projects: {
    title: 'Projets',
    description: "L'avancement de vos projets et les tâches partagées par l'équipe Lucid-Lab.",
    listTitle: 'Vos projets',
    empty: 'Aucun projet actif pour le moment.',
    typeLabels: {
      website: 'Site web',
      automation: 'Automatisation',
      agent: 'Agent IA',
      app: 'Application',
      strategy: 'Stratégie',
      ops: 'Opérations',
    } as Record<string, string>,
    statusLabels: {
      idea: 'En cadrage',
      planned: 'Planifié',
      active: 'En cours',
      blocked: 'En attente',
      completed: 'Livré',
      archived: 'Archivé',
    } as Record<string, string>,
  },

  tasks: {
    title: 'Tâches',
    todo: 'À faire',
    inProgress: 'En cours',
    waiting: 'En attente',
    done: 'Terminé',
    doneOn: 'Terminé le',
    due: 'Échéance',
    empty: 'Aucune tâche partagée pour le moment.',
    doneEmpty: 'Aucune tâche terminée pour le moment.',
  },

  documents: {
    title: 'Documents',
    description: 'Vos contrats, bons de commande et documents signés avec Lucid-Lab.',
    statusLabels: {
      sent_for_signature: 'À signer',
      viewed: 'À signer',
      in_progress: 'Signature en cours',
      signed: 'Signé',
      declined: 'Refusé',
      expired: 'Expiré',
      archived: 'Archivé',
    } as Record<string, string>,
    typeLabels: {
      bon_de_commande: 'Bon de commande',
      facture: 'Facture',
      contrat: 'Contrat',
      proposal: 'Proposition',
      other: 'Document',
    } as Record<string, string>,
    download: 'Télécharger le PDF',
    sign: 'Signer le document',
    signPending: 'Le lien de signature arrive, nous vous prévenons par email.',
    empty: 'Aucun document partagé pour le moment.',
    uploadTitle: 'Nous transmettre un document',
    uploadHint:
      "Un document signé, un justificatif, une pièce que nous vous avons demandée. Il arrive directement dans votre dossier et nous sommes prévenus. PDF, image ou document bureautique, 20 Mo maximum.",
    uploadFile: 'Fichier',
    uploadNote: 'Message (facultatif)',
    uploadNotePlaceholder: 'De quoi s’agit-il ?',
    uploadSubmit: 'Envoyer le document',
    uploadReceivedTitle: 'Documents que vous nous avez transmis',
    uploadOk: 'Document bien reçu. Nous avons été prévenus.',
    uploadErrors: {
      vide: 'Aucun fichier sélectionné.',
      empty: 'Le fichier est vide.',
      too_large: 'Le fichier dépasse 20 Mo.',
      type: 'Ce format de fichier n’est pas accepté.',
      storage: 'L’envoi a échoué. Réessayez, ou écrivez-nous depuis la page Support.',
    } as Record<string, string>,
  },

  billing: {
    title: 'Facturation',
    description: 'Vos documents commerciaux, leurs montants et le suivi des paiements.',
    documentsTitle: 'Documents',
    historyTitle: 'Suivi des paiements',
    statusLabels: {
      pending: 'En préparation',
      quoted: 'Devis envoyé',
      signed: 'Signé',
      invoiced: 'Facturé',
      due: 'À régler',
      paid: 'Payé',
      overdue: 'En retard',
      cancelled: 'Annulé',
    } as Record<string, string>,
    eventLabels: {
      bdc_drafted: 'Bon de commande préparé',
      bdc_sent: 'Bon de commande envoyé',
      bdc_signed: 'Bon de commande signé',
      invoice_generated: 'Facture émise',
      invoice_sent: 'Facture envoyée',
      payment_due: 'Paiement attendu',
      payment_received: 'Paiement reçu',
      payment_overdue: 'Paiement en retard',
      credit_note: 'Avoir émis',
      other: 'Facturation',
    } as Record<string, string>,
    setupLabel: 'mise en place',
    monthlyLabel: 'par mois',
    issuedOn: 'Émis le',
    dueOn: 'Échéance',
    signedOn: 'Signé le',
    empty: 'Aucun élément de facturation pour le moment.',
    historyEmpty: 'Aucun paiement enregistré pour le moment.',
  },

  requests: {
    title: 'Support',
    description: 'Créez un ticket, suivez nos réponses dans le fil de discussion et répondez à nos demandes.',
    newRequest: 'Nouveau ticket',
    fromYou: 'Vos tickets',
    fromUs: 'Demandes de Lucid-Lab',
    actionNeeded: 'Votre réponse est attendue',
    typeField: 'Type de demande',
    titleField: 'Objet',
    bodyField: 'Détail (optionnel)',
    priorityField: 'Priorité',
    submit: 'Envoyer le ticket',
    created: 'Votre ticket a bien été créé. Nous avons été prévenus et revenons vers vous rapidement.',
    responded: 'Merci, votre réponse a bien été enregistrée.',
    messageSent: 'Votre message a bien été envoyé. Nous avons été prévenus.',
    resolvedByYou: 'Merci, le ticket est marqué comme résolu.',
    approve: 'Approuver',
    markDone: "C'est fait",
    requestChanges: 'Demander des modifications',
    askQuestion: "J'ai une question",
    noteOptional: 'Commentaire (optionnel)',
    noteRequired: 'Précisez votre demande ou votre question',
    ourResponse: 'Réponse de Lucid-Lab',
    yourResponse: 'Votre réponse',
    sentOn: 'Envoyée le',
    back: 'Retour au support',
    notFound: 'Cette demande est introuvable.',
    thread: 'Fil de discussion',
    reply: 'Répondre',
    replyPlaceholder: 'Votre message...',
    markResolved: 'Marquer comme résolu',
    markResolvedHint: 'Le sujet est réglé pour vous ? Fermez le ticket, nous en serons informés.',
    closedNotice: 'Cet échange est clos. Créez un nouveau ticket si besoin.',
    you: 'Vous',
    statusLabels: {
      open: 'Ouvert',
      in_progress: 'En cours',
      waiting: 'En attente de votre réponse',
      approved: 'Approuvé',
      changes_requested: 'Modifications demandées',
      done: 'Résolu',
      declined: 'Décliné',
    } as Record<string, string>,
    typeLabels: {
      question: 'Question',
      change_request: 'Demande de modification',
      incident: 'Incident',
      asset_request: 'Éléments à fournir',
      approval: 'Validation',
      info_request: 'Informations à compléter',
    } as Record<string, string>,
    priorityLabels: {
      low: 'Basse',
      normal: 'Normale',
      high: 'Haute',
      urgent: 'Urgente',
    } as Record<string, string>,
    empty: 'Aucun ticket pour le moment.',
  },

  meetings: {
    empty: 'Aucun compte rendu de réunion pour le moment.',
    recordedOn: 'Réunion du',
  },

  info: {
    title: 'Mes informations',
    description: 'Vérifiez les informations de votre entreprise et transmettez-nous du contexte utile : tout arrive directement dans votre dossier chez Lucid-Lab.',
    companyTitle: 'Votre entreprise',
    legalName: 'Raison sociale',
    siren: 'SIREN',
    siret: 'SIRET',
    billingAddress: 'Adresse de facturation',
    websiteUrl: 'Site web',
    save: 'Envoyer la correction',
    saveHint: "Vos corrections nous sont transmises pour vérification, puis appliquées à votre dossier. Rien n'est modifié sans notre contrôle.",
    pendingNotice: "Votre correction est en attente de validation. C'est elle qui s'affiche ci-dessous. Elle sera appliquée à votre dossier dès que nous l'aurons vérifiée.",
    saved: 'Correction transmise. Nous la vérifions et nous appliquons la mise à jour.',
    saveFailed: "Les informations n'ont pas pu être transmises. Réessayez ou écrivez-nous.",
    contextTitle: 'Transmettre des informations',
    contextHint: 'Votre activité, vos outils, vos objectifs, une actualité : tout ce qui nous aide à mieux vous accompagner.',
    contextPlaceholder: 'Écrivez librement ici...',
    send: 'Envoyer',
    contextSent: 'Bien reçu, merci ! Nous en tenons compte dans votre dossier.',
  },

  website: {
    title: 'Site web',
    description: "L'état de votre site géré par Lucid-Lab.",
    statusLabels: {
      planned: 'Prévu',
      designing: 'En design',
      building: 'En construction',
      live: 'En ligne',
      paused: 'En pause',
      archived: 'Archivé',
    } as Record<string, string>,
    healthLabels: {
      unknown: 'Surveillance à venir',
      healthy: 'Opérationnel',
      degraded: 'Dégradé',
      down: 'Indisponible',
    } as Record<string, string>,
    domainsTitle: 'Domaines',
    sslLabel: 'SSL',
    expiresOn: 'Expire le',
    lastChecked: 'Vérifié le',
    visit: 'Voir le site',
    empty: 'Aucun site géré pour le moment.',
  },

  assistant: {
    title: 'Assistant Lucid-Lab',
    open: "Ouvrir l'assistant",
    close: "Fermer l'assistant",
    intro: "Bonjour ! Posez votre question. Si l'équipe doit intervenir, je crée un ticket et elle est prévenue immédiatement.",
    placeholder: 'Écrivez votre message...',
    send: 'Envoyer',
    thinking: "L'assistant écrit...",
    error: "L'assistant est momentanément indisponible. Réessayez, ou créez un ticket depuis la page Support.",
    readOnly: 'Aperçu lecture seule : le chat est désactivé.',
    viewTicket: 'Voir le ticket',
  },

  footer: {
    contact: 'Une question ? Écrivez-nous à info@lucid-lab.fr',
    site: 'lucid-lab.fr',
  },
} as const;

export type PortalStrings = typeof portalStrings;
